DynamicContentData { iso(1) identified-organization(3) dod(6)
    internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) dcd(3) v2(2) 0 }
    DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS UICDynamicContentData;
IMPORTS Timestamp, GeoCoordinate, Data, DataFormatIdentifier
 FROM GeneralData { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) general(5) v1(1) 0 }
 LEVEL-2-DATA-ELEMENT
 FROM BarcodeHeader { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) header(1) v3(3) 0 };

DynamicContent ::= SEQUENCE {
    /**
    * Identification of the mobile application that generated the barcode and filled in the dynamic part.
    * Values as defined by the security provider.
    */
    dynamicContentMobileAppId           VisibleString       OPTIONAL,

    /**
    * Generation time of the dynamic content.
    */
    dynamicContentTimeStamp             Timestamp           OPTIONAL,

    /**
    * Coordinates of the location where the dynamic content was been generated.
    */
    dynamicContentGeoCoordinate         GeoCoordinate       OPTIONAL,

    dynamicContentResponseToChallenge   SEQUENCE OF Data{RESPONSE-TO-CHALLENGE},

    ...
}

dynamicContentData LEVEL-2-DATA-ELEMENT ::= { DynamicContent IDENTIFIED BY "FDC2" }

RESPONSE-TO-CHALLENGE ::= CLASS {
    &id DataFormatIdentifier (ALL EXCEPT ("!I" | "!C" | "!P")) UNIQUE,
    &Type
} WITH SYNTAX {
    &Type IDENTIFIED BY &id
}

END