DynamicContentData { iso(1) identified-organization(3) dod(6)
    internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) dcd(3) v2(2) 0 }
    DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS DynamicContent, dynamicContentData;
IMPORTS Timestamp, GeoCoordinate, Data, DATA-ELEMENT, cuperEncoding
 FROM GeneralData { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) general(5) v1(1) 0 };

DynamicContent ::= SEQUENCE {
    /**
    * Identification of the mobile application that generated the barcode and filled in the dynamic part.
    * Values as defined by the security provider.
    */
    dynamicContentMobileAppId           VisibleString       OPTIONAL,

    /**
    * Generation time of the dynamic content.
    */
    dynamicContentTimeStamp             Timestamp           OPTIONAL,

    /**
    * Coordinates of the location where the dynamic content was been generated.
    */
    dynamicContentGeoCoordinate         GeoCoordinate       OPTIONAL,

    dynamicContentResponseToChallenge   SEQUENCE OF Data{ResponsesToChallenge} (WITH COMPONENTS {
        ...,
        format (ALL EXCEPT ("!I" | "!C" | "!P"))
    }),

    ...
}

dynamicContentData DATA-ELEMENT ::= { DynamicContent IDENTIFIED BY "FDC2" ENCODED WITH cuperEncoding }

ResponsesToChallenge DATA-ELEMENT ::= { ... }

END