BT4PT-DynamicContentDataV1-0 {
    iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) dcd(4) v1(1) 0
} DEFINITIONS ::= BEGIN

EXPORTS DynamicContent, dynamicContentData, dynamicContentDataAligned;
IMPORTS Timestamp, GeoCoordinate, Data, DATA-ELEMENT, cuperEncoding, caperEncoding
 FROM BT4PT-GeneralElementsV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) general(1) v1(1) 0 };

DynamicContent ::= SEQUENCE {
    /**
    * Identification of the mobile application that generated the barcode and filled in the dynamic part.
    * Values as defined by the security provider.
    */
    dynamicContentMobileAppId           VisibleString       OPTIONAL,

    /**
    * Coordinates of the location where the dynamic content was been generated.
    */
    dynamicContentGeoCoordinate         GeoCoordinate       OPTIONAL,

    dynamicContentResponseToChallenge   SEQUENCE OF Data{ResponsesToChallenge} (WITH COMPONENTS {
        ...,
        format (ALL EXCEPT ("!I" | "!C" | "!P"))
    }),

    /**
    * A unique ID for this instance of a dynamic barcode (i.e. updated each time the dynamic segment is regenerated).
    * This field **SHALL NOT** be used in assessing the validity of a ticket, it exists for debugging purposes.
    * This field has no relation to any ticket ID in any ticket control database.
    */
    dynamicContentId                    GenericId           OPTIONAL,

    /**
    * Traceability information linked to the about the application that generated the barcode and filled in the dynamic part.
    * Values as defined by the security provider.
    * This field **SHALL NOT** be used in assessing the validity of a ticket, it exists for debugging purposes.
    */
    dynamicContentTraceability          VisibleString       OPTIONAL,

    ...
}

dynamicContentData DATA-ELEMENT ::= { DynamicContent IDENTIFIED BY "DCD1" ENCODED WITH cuperEncoding CONSTRAINED BY NULL }
dynamicContentDataAligned DATA-ELEMENT ::= { DynamicContent IDENTIFIED BY "DCD1A" ENCODED WITH caperEncoding CONSTRAINED BY NULL }

ResponsesToChallenge DATA-ELEMENT ::= { ... }

END