/**
* BT4PT Barcode Header - DRAFT.
*
* The header **SHALL** be encoded with the Aligned Packed Encoding Rules, as this makes it easier to work with in constrained environments such as HSMs.
* Data elements within the header **SHOULD** be encoded with the Unaligned Packed Encoding Rules, for space savings.
*/
BT4PT-BarcodeHeaderV1-0 {
    iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) header(2) v1(1) 0
} DEFINITIONS ::= BEGIN

EXPORTS BarcodeHeader;
IMPORTS CompanyCode, Timestamp, Data, DATA-ELEMENT
 FROM BT4PT-GeneralElementsV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) general(1) v1(1) 0 }
 EndEntityCertificate
 FROM BT4PT-CertificatesV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) certificates(7) v1(1) 0 }
 multiModalTicketData
 FROM BT4PT-MultiModalTicketDataV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) mmtd(3) v1(1) 0 }
 dynamicContentData, dynamicContentDataAligned
 FROM BT4PT-DynamicContentDataV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) dcd(4) v1(1) 0 }
 fixedPointData
 FROM BT4PT-FixedPointDataV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) fpd(5) v1(1) 0 }
 hsmTraceData
 FROM BT4PT-HSMTraceV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) hsm(6) v1(1) 0 }
 uicRailTicketData
 FROM RailTicketDataV3 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) rtd(2) v3(3) 7 }
 uicRailTicketData
 FROM RailTicketDataV2 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) rtd(2) v2(2) 3 }
 uicRailTicketData
 FROM RailTicketDataV1 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) rtd(2) v1-3(1) 5 }
 uicDynamicContentData
 FROM DynamicContentDataV1 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) dcd(3) v1(1) 5 };

/**
* The basic entry point of the barcode.
*/
BarcodeHeader ::= SEQUENCE {
    /**
    * This field **SHALL** be set to the byte string `U3`.
    * This results in this barcode header being prefixed with U3 at the start, allowing identification of this
    *  format of barcode header.
    */
    format      OCTET STRING (SIZE(2)),
    contents    CHOICE {
        /**
        * Only permitted where no security is required.
        */
        unsigned    [1] SEQUENCE (SIZE(1..16)) OF Data{{IssuerDataElements}} (WITH COMPONENTS {
            ...,
            format (ALL EXCEPT ("!I" | "!C" | "!P"))
        }),
        signed      [2] SEQUENCE {
            data            DeviceSignedData,
            /**
            * If the the `IssuerSignedData.deviceBinding` field is unset, and this field is set, the barcode is invalid.
            * If the the `IssuerSignedData.deviceBinding` field is set, and this field is unset, the barcode is invalid.
            * The signature is calculated over the A-PER encoding of `DeviceSignedData`.
            */
            deviceSignature Signature OPTIONAL
        }
    }
}

DeviceSignedData ::= SEQUENCE {
    /**
    * Signed content is the A-PER encoding of `IssuerSignedData`.
    */
    data        MessageRecoverySignature,
    certificate EndEntityCertificate,
    /**
    * Generation time of the device data. **MUST** be set if `IssuerSignedData.deviceBinding` is set, otherwise the barcode is invalid.
    */
    timestamp   Timestamp   OPTIONAL,
    /**
    * Dynamic Content Data goes here.
    *
    * Note: the inclusion of device data without the `IssuerSignedData.deviceBinding` field being set is **not** an error.
    * It is permissible to include unauthenticated device data, for example as a debugging aid.
    */
    deviceData  SEQUENCE (SIZE(1..8)) OF Data{{DeviceDataElements}} (WITH COMPONENTS {
        ...,
        format (ALL EXCEPT ("!I" | "!C" | "!P"))
    }) OPTIONAL
}


IssuerSignedData ::= [APPLICATION 12] SEQUENCE {
    data                SEQUENCE (SIZE(1..64)) OF Data{{IssuerDataElements}} (WITH COMPONENTS {
        ...,
        format (ALL EXCEPT ("!I" | "!C" | "!P"))
    }),
    /**
    * End of the validity of the barcode.
    * After this date and time the barcode needs to be regenerated by the provider of the ticket.
    * The provider of the bar code **MUST** ensure that the endOfValidity given here does not exceed the validity of the key pair used on level 2.
    */
    endOfValidity       Timestamp   OPTIONAL,
    deviceBinding       [1] SEQUENCE {
        level2PublicKey     CHOICE {
            nistP256    [1] ECPublicKey{32},
            secp256K1   [2] ECPublicKey{32},
            nistP384    [3] ECPublicKey{48},
            nistP521    [4] ECPublicKey{66},
            ed25519     [5] OCTET STRING (SIZE (32)),
            ed448       [6] OCTET STRING (SIZE (57)),
            /**
            * DER encoded SubjectPublicKeyInfo.
            */
            other       [7] OCTET STRING
        },
        /**
        * Validity duration in seconds of the barcode with reference to the time stamp in the dynamic content data.
        */
        validityDuration    INTEGER (1..3600)
   	} OPTIONAL
}

IssuerDataElements DATA-ELEMENT ::= {
    multiModalTicketData |
    fixedPointData |
    hsmTraceData,
    --RailTicketDataV3.uicRailTicketData |
    --RailTicketDataV2.uicRailTicketData |
    --RailTicketDataV1.uicRailTicketData,
    ...
}

DeviceDataElements DATA-ELEMENT ::= {
    dynamicContentData |
    dynamicContentDataAligned,
    --DynamicContentDataV1.uicDynamicContentData,
    ...
}

/**
* A generic container for the conveyance of Digital Signature Scheme signatures, i.e. ECDSA.
* @len The length, in bytes, of each of `r` and `s`. That is, half the total signature length.
*/
DSSSignature{INTEGER: len} ::= SEQUENCE {
    r OCTET STRING (SIZE(len)),
    s OCTET STRING (SIZE(len))
}

Signature ::= CHOICE {
    /**
    * ECDSA using the NIST P-256 curve and SHA-256.
    */
    es256       [1] DSSSignature{32},
    /**
    * ECDSA using the secp256k1 curve and SHA-256.
    */
    es256k      [2] DSSSignature{32},
    /**
    * ECDSA using the NIST P-384 curve and SHA-384.
    */
    es384       [3] DSSSignature{48},
    /**
    * ECDSA using the NIST P-521 curve and SHA-512.
    */
    es512       [4] DSSSignature{66},
    /**
    * EdDSA over Curve25519.
    */
    ed25519     [5] OCTET STRING (SIZE (64)),
    /**
    * EdDSA over Curve448.
    */
    ed448       [6] OCTET STRING (SIZE (114)),
    other       [7] SEQUENCE {
        algId       OBJECT IDENTIFIER,
        signature   OCTET STRING
    }
}

/**
* Message recovery signature as per ISO/IEC 9796-3:2006 Sec. 13 (ECKNR).
* @len The length, in bytes, of each of `r` and `s`. That is, half the total signature length.
*/
ECKNRSignature{INTEGER: len} ::= SEQUENCE {
    r OCTET STRING (SIZE(len)),
    s OCTET STRING (SIZE(len)),
    remainder OCTET STRING
}

MessageRecoverySignature ::= [APPLICATION 11] CHOICE {
    /**
    * NIST P-256 curve and SHA-256.
    */
    es256   [1] ECKNRSignature{32},
    /**
    * secp256k1 curve and SHA-256.
    */
    es256k  [2] ECKNRSignature{32},
    /**
    * NIST P-384 curve and SHA-384.
    */
    es384   [3] ECKNRSignature{48},
    /**
    * NIST P-521 curve and SHA-512.
    */
    es512   [4] ECKNRSignature{66}
}

/**
* @len The length, in bytes, required to represent the x coördinate on a curve.
*/
ECPublicKey{INTEGER: len} ::= SEQUENCE {
    yIsOdd BOOLEAN,
    x OCTET STRING (SIZE(len))
}

END
