/**
* BT4PT Certificates - DRAFT.
*/
BT4PT-CertificatesV1-0 {
    iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) certificates(7) v1(1) 0
} DEFINITIONS ::= BEGIN

EXPORTS EndEntityCertificate;
IMPORTS CompanyCode, Data, ECPublicKey, DataAuthorization, UnicodeText, DATA-ELEMENT, cuperEncoding, nullEncoding
 FROM BT4PT-GeneralElementsV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) general(1) v1(1) 0 }
 IssuerDataElements
 FROM BT4PT-BarcodeHeaderV1-0 { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) bt4pt(2) header(2) v1(1) 0 };

EndEntityCertificate ::= SEQUENCE {
    serial                      INTEGER (1..16777216),
    issuingSecurityProvider     CompanyCode,
    caId                        INTEGER (1..65536),
    validUntilYear              INTEGER (2026..2281),
    validUntilDay               INTEGER (1..366),
    /**
    * The public key **MUST** be of the same EC curve as the issuing certificate's public key.
    * If it is not the certificate **MUST** be treated as invalid.
    * This public key is calculated as per [SEC 4](https://www.secg.org/sec4-1.0.pdf).
    */
    publicKeyReconstructionData CHOICE {
        nistP256    [1] ECPublicKey{32},
        secp256K1   [2] ECPublicKey{32},
        nistP384    [3] ECPublicKey{48},
        nistP521    [4] ECPublicKey{66}
    },
    extensions                  SEQUENCE (SIZE(0..15)) OF CertificateExtension
}

/**
* A certificate extension, containing data as specified by its `&Type`, and encoded into an `OCTET STRING` as specified by its `&encoding`.
* When included in an `EndEntityCertificate` it is identified by its `&id`.
* If `&id` is not set, then the extension may not appear in an `EndEntityCertificate`, only an X.509 certificate.
* When included in an X.509 certificate, it is identified by its `&oid`.
* The identifier `&id` can be of the following forms:
* - `+` + [2-letters uppercase ISO 3166 country code] + [addon, chosen by the national standards body of that country]
* - `_` + [RICS or ERA Organisation Code] + [addon, chosen by this company]
* - `*` + [addon] - private use, not guaranteed to avoid clashes.
*
* Any other value only after registration in the appropriate registry.
* Unregistered values (outside of the national, company, and private use ranges) **MUST NOT** be used.
* If an organisation has a RICS or an ERA Organisation Code the private use format **MUST NOT** be used.
* All values **SHOULD** be registered via the UIC Github repository.
*/
CERTIFICATE-EXTENSION ::= CLASS {
    &id VisibleString (SIZE(1..8)) UNIQUE OPTIONAL,
    &oid OBJECT IDENTIFIER UNIQUE,
    &Type,
    &encoding OBJECT IDENTIFIER
} WITH SYNTAX {
    &Type [IDENTIFIED BY &id] WITH OID &oid ENCODED WITH &encoding
}

CertificateExtension ::= [APPLICATION 3] SEQUENCE {
    /**
    * If the data format is not recognised, or can't be processed, and it is marked critical, the certificate **MUST** be treated as invalid;
    * otherwise, it is permitted to ignore extensions not understood.
    */
    critical    BOOLEAN,
    format      CERTIFICATE-EXTENSION.&id({EECertificateExtensions}),
    value       OCTET STRING (CONTAINING CERTIFICATE-EXTENSION.&Type({EECertificateExtensions}{@format}))
}

EECertificateExtensions CERTIFICATE-EXTENSION ::= {
    specimenPoisonExt |
    issuerDataAuthorizationExt,
    ...
}

CertificateExtensions CERTIFICATE-EXTENSION ::= {
    specimenPoisonExt |
    issuerDataAuthorizationExt |
    certificateIdExt |
    eeCertCRLExt,
    ...
}

bt4ptPkiExt OBJECT IDENTIFIER ::= {iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1)
    uic(17218) fcb(1) bt4pt(2) pkiExt(9)}

/**
* Any barcode signed by a certificate containing this poison marker **MUST** be considered a specimen barcode,
* regardless of any other specimen flag.
*/
specimenPoisonExt CERTIFICATE-EXTENSION ::= { NULL IDENTIFIED BY "SP" WITH OID {bt4ptPkiExt specimenPoison(0)} ENCODED WITH nullEncoding }

/**
* This extension specifies which issuer data elements may be included in a barcode signed by this certificate, and
* what constraints apply to them.
*/
issuerDataAuthorizationExt CERTIFICATE-EXTENSION ::= { DataAuthorization{{IssuerDataElements}} IDENTIFIED BY "ID" WITH OID {bt4ptPkiExt issuerDataAuthorization(1)} ENCODED WITH cuperEncoding }

CertificateId ::= SEQUENCE {
    issuingSecurityProvider     CompanyCode,
    caId                        INTEGER (1..65536)
}

certificateIdExt CERTIFICATE-EXTENSION ::= { CertificateId WITH OID {bt4ptPkiExt certificateId(2)} ENCODED WITH cuperEncoding }

/**
* This extension contains the HTTP(S) URL at which the X.509 Certificate Revocation List for end-entity certificates
* directly issued by this CA may be retrieved.
*/
eeCertCRLExt CERTIFICATE-EXTENSION ::= { VisibleString WITH OID {bt4ptPkiExt eeCertCRL(3)} ENCODED WITH cuperEncoding }

/**
* This extension defines a notice to be displayed to inspection staff upon encountering a revoked certificate.
* It is to be included as an extension to a Certificate Revocation List Entry.
* Each entry in the `localisedNotices` **SHOULD** convey the same information in a different language.
* The device performing the ticket validation can select which language, of those provided, is most appropriate to be
* displayed.
*/
RevocationNotice ::= SEQUENCE {
    localisedNotices    SEQUENCE OF UnicodeText
}

revocationNoticeExt CERTIFICATE-EXTENSION ::= { RevocationNotice WITH OID {bt4ptPkiExt revocationNotice(4)} ENCODED WITH cuperEncoding }

END